# Generated by Django 5.0.6 on 2024-08-24 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('goat_age', models.IntegerField(default=0)),
                ('grass_num', models.IntegerField(default=0)),
                ('garden_array', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), blank=True, null=True, size=9)),
                ('subscription_end_date', models.DateField(null=True)),
                ('donated_goat_num', models.IntegerField(default=0)),
            ],
        ),
    ]
