# Generated by Django 5.0.6 on 2024-08-24 09:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_garden_array_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='garden_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(max_length=1), default=[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False], size=81),
        ),
    ]
