# Generated by Django 5.0.6 on 2024-08-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_garden_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='garden_array',
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
