# Generated by Django 5.0.6 on 2024-08-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='garden_array',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
