# Generated by Django 5.0.6 on 2024-08-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_garden_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grass_num',
        ),
        migrations.AddField(
            model_name='user',
            name='hay_num',
            field=models.IntegerField(default=10),
        ),
    ]
